{
 "title": "huawei_lte_exporter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Cell ID", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cell ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "sum without (band) (cell_id)", "legendFormat": "Cell ID" }
   ]
  },
  {
   "title": "Cell ID",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum without (band) (cell_id)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "4G",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "sinr",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum without (band) (sinr)" }
   ]
  },
  {
   "title": "rsrq",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum without (band) (rsrq)" }
   ]
  },
  {
   "title": "rssi",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum without (band) (rssi)" }
   ]
  },
  {
   "title": "rsrp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum without (band) (rsrp)" }
   ]
  },
  {
   "title": "4G RSRQ & SINR by Band",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    { "expr": "sum without (band) (rsrq{})", "legendFormat": "rsrq {{band}}" },
    { "expr": "sum without (band) (sinr{})", "legendFormat": "sinr {{band}}" }
   ]
  },
  {
   "title": "4G RSRP &  RSSI by Band",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    { "expr": "sum without (band) (rsrp{})", "legendFormat": "rsrp {{band}}" },
    { "expr": "sum without (band) (rssi{})", "legendFormat": "rssi {{band}}" }
   ]
  },
  {
   "title": "4G Band",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "band{}" }
   ]
  },
  {
   "title": "3G",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "rssi",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "dB" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum without (band) (rssi)" }
     ]
    },
    {
     "title": "rscp",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum without (band) (rscp)" }
     ]
    },
    {
     "title": "ec/io",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "dB" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum without (band) (ecio)" }
     ]
    }
   ]
  },
  { "title": "Transfers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Transfer rates (reported)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum without (band) (download_rate)",
     "legendFormat": "Download rate"
    },
    {
     "expr": "sum without (band) (upload_rate)",
     "legendFormat": "Upload rate"
    }
   ]
  },
  {
   "title": "Transfer rates (inferred)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum without (band) (irate(total_download[2m]))",
     "legendFormat": "Download rate"
    },
    {
     "expr": "sum without (band) (irate(total_upload[2m]))",
     "legendFormat": "Upload rate"
    }
   ]
  }
 ]
}